name: Stok Takip
version: "1.11"
slug: stock_watcher
description: Verilen ürün linkini saat başı kontrol eder ve ürün stoğa girince Pushover bildirimi gönderir.
url: https://github.com/nriacr/stock-watcher/tree/main/stock-watcher
arch:
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
init: false
options:
  pushover_user_key: ""
  pushover_api_token: ""
  request_timeout_seconds: 20
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  products:
    - name: "Ürün 1"
      enabled: true
      url: ""
      notify_once_in_24h: true
      check_interval_minutes: 60
      in_stock_keywords:
        - "sepete ekle"
        - "stokta"
        - "hemen al"
        - "add to cart"
        - "in stock"
      out_of_stock_keywords:
        - "stokta yok"
        - "tükendi"
        - "geçici olarak temin edilemiyor"
        - "out of stock"
        - "sold out"
schema:
  pushover_user_key: password
  pushover_api_token: password
  request_timeout_seconds: int(5,120)
  user_agent: str
  products:
    - name: str
      enabled: bool?
      url: str
      notify_once_in_24h: bool?
      check_interval_minutes: int(5,1440)
      in_stock_keywords:
        - str
      out_of_stock_keywords:
        - str
